### ISSUE TITLE
Chrome nn-passive event listener warning

### ISSUE THREAD

**Issue by djeetee** [shaack/cm-chessboard#114]
I have been ignoring the following warning that only shows up in chrome but now I need to figure out if it's because I'm doing or what.

the warning pops up in the console right after initializing a board.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/612096/236653303-faf3b254-a1c1-4340-9ab6-2decc5eb91e9.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/612096/236679779-e8e9e901-bacb-4d28-8961-7c5e1d9a717a.png">

has anyone come across this?

thanks.

**Comment by shaack** [comment]
Hi!  This warning seems to be quite new in Chrome. The fix may be easy to add `{passive: true}` options to the event listeners, but I am not sure how to deal with it because I am not sure what it means in its entirety to make a listener passive. I will read a few lines about it and then I will just try it out.

**Comment by djeetee** [comment]
fyi, FF doesn't show the warning. thanks for looking into this.

**Comment by shaack** [comment]
Okay, as I understand, the point is, that an `passive` event can not handle the `preventDefault()` command. But in cm-chessboard, wie _need_ to prevent scrolling, when someone makes a move. So the question is, how to get rid of those warnings.

**Comment by shaack** [comment]
Fixed this by adding `{passive: false}` to the event listeners with version v7.3.17.

**Comment by djeetee** [comment]
Thank you!
