### ISSUE TITLE
Capablanca chessboard implementation

### ISSUE THREAD

**Issue by programarivm** [shaack/cm-chessboard#141]
👋 Hey there,

Classical chess has become a concern in terms of cheating. However, [Capablanca chess](https://en.wikipedia.org/wiki/Capablanca_chess) and [Capablanca-Fischer chess](https://github.com/chesslablab/php-chess/blob/main/tests/unit/Variant/CapablancaFischer/BoardTest.php) increase the probability space of the chess moves available making cheating impossible.

See:

- [Chess Variants](https://chesslablab.github.io/php-chess/#chess-variants)

![figure_02](https://github.com/shaack/cm-chessboard/assets/4062000/a929ae93-01e4-4c06-9435-f71c2a82b7c1)

I was wondering if it'd be possible to add a Capablanca board to cm-chessboard.

👍 Keep it up,

**Comment by shaack** [comment]
Okay, this is huge. Because, for me, it would mean to create a layer above the cm-chessboard. Like "cm-gameboard" to implement the main behavior and view of a board independent of the number of squares or pieces. This however could also be used to implement other games like checkers, Chinese chess, Go or Capablanca chess.
