### ISSUE TITLE
Suggestion: Add highlight system

### ISSUE THREAD

**Issue by xFighter1209** [shaack/cm-chessboard#54]
I suggest having highlight system for highlighting previous moves. If I use marker class for highlighting previous moves, it would be ugly because markerclass is for marking squares by the move input.

**Comment by shaack** [comment]
First, did you read the documentation about „Create your own custom markers“?

**Comment by shaack** [comment]
This is done in chess-console, which uses cm-chessboard. https://github.com/shaack/chess-console 
Example: https://shaack.com/projekte/chess-console/examples/play-both-local.html

**Comment by vesper8** [comment]
@shaack Thank you

I also found this older example that does this and more https://codesandbox.io/s/fwmc8?file=/src/chessboard.js

I get the sense though that ever since you added the new marker system, it's no longer so easy to set the background colour of squares?

If you see here: https://codesandbox.io/s/fwmc8?file=/src/chessboard.js:1562-1612

It used to be very straight forward to set the background color of any square.

Is that still possible now? If I don't want to add a marker per se (a shape) but just want to set or toggle the background color of a square. Can I do that without first creating a custom marker and creating a class? Is it possible to just do it inline like in the above example?

Many thanks

**Comment by djeetee** [comment]
is [https://shaack.com/projekte/cm-chessboard/examples/input-callbacks.html](url) available? it's not in the examples (or is it?)

thanks

**Comment by shaack** [comment]
I think this was moved to https://shaack.com/projekte/cm-chessboard/examples/extensions/markers-extension.html
