### ISSUE TITLE
Snapback animation if move was cancelled.

### ISSUE THREAD

**Issue by designingSparks** [shaack/cm-chessboard#55]
How would this be done? It would look nicer to animate the piece back to it's original position if the move were invalid for example.

**Comment by shaack** [comment]
An animation after a wrong move has been executed would have some effects that are overlooked at first sight. When a change is animated, it costs time. Time in which it is not possible to perform another animations or you would have to cancel the animation. I suspect such a snap back animation would be far too complicated and time consuming to implement properly. But I mean, you are welcome to try it, I on the other hand will not implement it because I never missed it.
