### ISSUE TITLE
how to import arrows extension in Vue from node_modules

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#79]
I see that you suggest we import cm-chessboard like so:

```

import {Chessboard} from "./src/cm-chessboard/Chessboard.js"
```

But I prefer to do it like this:
```
import { Chessboard } from "cm-chessboard";
```

Which works fine and loads it from the node_modules folder

However when I tried to make the Arrows extension work which you suggest we import like this:

```
import {ARROW_TYPE, Arrows} from "./src/cm-chessboard/extensions/arrows/Arrows.js"
```

I couldn't get it to work. I tried multiple variations such as

```
import {ARROW_TYPE, Arrows} from "/cm-chessboard/extensions/arrows/Arrows"
and
import {ARROW_TYPE, Arrows} from "/cm-chessboard/extensions/arrows"
and
import {ARROW_TYPE, Arrows} from "/cm-chessboard/extensions"
```

But none of them worked. Finally I got it to work like this:

```

import { ARROW_TYPE, Arrows } from "../../node_modules/cm-chessboard/src/cm-chessboard/extensions/arrows/Arrows.js";
```

but this is super hacky and looks very wrong.

Could you by any chance advise how to import the arrows extension from the node_modules folder?

Many thanks!

**Comment by shaack** [comment]
In the ES6 specification an import like `import { Chessboard } from "cm-chessboard"` is not specified, it is a transpiling or nodejs thing. Therefore an import like `import { ARROW_TYPE, Arrows } from "../../node_modules/cm-chessboard/src/cm-chessboard/extensions/arrows/Arrows.js"` looks correct for me. All includes in my ES6 projects are relative. To not include them from `node_modules` I use [ModLib](https://github.com/shaack/modlib), it copies the relevant src-files to a `lib` folder on `npm install`.

**Comment by vesper8** [comment]
It doesn't look right to me, what is the point of copying files from the node_modules to a lib folder when you can just load them from the node_modules folder? This makes sense in cases where you've forked something, or if the package is private and not on npm. Importing packages using 

```
import { Chessboard, COLOR, BORDER_TYPE, MARKER_TYPE } from "cm-chessboard";
``` 

feels right and feels like the standard way to do imports. It may be that in your personal projects you copy everything to a relative folder such as lib but that seems rather unconventional and a bit puzzling, I don't understand why.

I managed to make it a tiny bit cleaner by creating an alias to the node_modules folder so I am now able to do this

```

import { ARROW_TYPE, Arrows } from "~/cm-chessboard/src/cm-chessboard/extensions/arrows/Arrows.js";
```


But what I would really like to do is this


```

import { ARROW_TYPE, Arrows } from "cm-chessboard/extensions/arrows/Arrows.js";
```


I hope you consider making this possible. Or what you could do is simply publish the extensions as individual packages so we can then do something like this

```

import { ARROW_TYPE, Arrows } from "cm-chessboard-extensions-arrows";
```

That would be equally great.

Anyway, still loving your work here and am very grateful. Just wanted to point out this inconsistency which is rather non-standard compared to hundreds of other packages I'm currently using.

Kind regards

**Comment by shaack** [comment]
Thanks for your interest to my work and your enquiry. :) I will try to give you some answers.

> what is the point of copying files from the node_modules to a lib folder

I have many ES6 projects which are dependent ("chess-console", "cm-pgn", "cm-chess", "cm-chessboard",...) and all are published on npm. ES6 works in all modern browsers without transpiling, so I wanted to get my projects and dependencies to work out of the box, in vanilla JS. I don't like transpiling while developing, it makes everything twice complicated.

**The problem**

Lets assume we have two ES6 projects. "cm-main" and "cm-dependecy" with the following structure:
"cm-main/src/Main.js" and "cm-dependency/src/Dependency.js".

When developing "cm-main" the import path from "src/Main.js" to "node_modules/cm-dependency/src/Dependency.js" would be "../node_modules/cm-dependency/src/Dependency.js" but later when both are npm packages, they are both in node_modules and then the import path will become "../../cm-dependency/Dependency.js". Because of that importing files from node_modules does not work for ES6 web-projects.

**The solution (without transpiling)**

When we copy "node_modules/cm-dependency/src/Dependency.js" to "lib/Dependency.js" on "npm install", the include path for local development from "src/Main.js" will be "../lib/Dependency.js". Later, when both are npm packages, the include path from "lib/Main.js" will remain "../lib/Dependency.js".

Maybe I missed something, but this idea works for me.

This syntax `import { Chessboard, COLOR, BORDER_TYPE, MARKER_TYPE } from "cm-chessboard"` is, IMHO not possible with standard ES6, because ES6 does not _know_ anything about a node_modules folder. Therefore I don't use this webpack/babel/node.js syntax, I only want to use vanilla JS in ES6 to keep things simple.

If you want to use this kind of import syntax, I am sorry and can not help you. You have to find a solution in the documentation of the transpiling software.

**Comment by MrEnroke** [comment]
@vesper8  I use webpack and to do what you ask I just add an alias:

```
resolve: {
	extensions: ['*', '.js', '.vue', '.json'],
	alias: {
		'@scripts': path.resolve('src/web-resources/scripts/'),
		'@styles': path.resolve('src/web-resources/styles/'),
		**'@nodemodules': path.resolve('node_modules')**
	}
}
```

And in my component: 
`import { ARROW_TYPE, Arrows } from '@nodemodules/cm-chessboard/src/cm-chessboard/extensions/arrows/Arrows.js';`

**Comment by shaack** [comment]
@vesper8 Does this answer your question and can I close the ticket?

**Comment by vesper8** [comment]
yea it's good enough, I understand your explanation and am ok with the workaround. I do stand by what I said above which is that this way of importing is unconventional and not representative of how npm packages are imported in general.
