### ISSUE TITLE
`getPosition` in `INPUT_EVENT_TYPE.moveDone` returns the position before the move

### ISSUE THREAD

**Issue by MrEnroke** [shaack/cm-chessboard#83]
Moves that require multiple squares, such as castling or en passant, are not fully updated. If in the validate-moves.html example we increase the Timeout time, the problem can be clearly seen.

![image](https://user-images.githubusercontent.com/4182336/186334646-c88ee0aa-a55d-48c9-a378-2cdd6e8b35c2.png)

If we try to do board.setPosition(fen) we get the problem that the board has changed.

![image](https://user-images.githubusercontent.com/4182336/186335319-8b44e517-41ef-498a-929f-5aa2bd8912a0.png)

What would be the correct way to make it work without error?

**Comment by shaack** [comment]
Which Timeout did you increase? I can't recreate that.

**Comment by shaack** [comment]
It looks like a kind of timing problem. In the `inputHandler(event)` on INPUT_EVENT_TYPE.moveDone the `event.chessboard.getPosition()` has the position before the move but should have the position after the move.

**Comment by MrEnroke** [comment]
But the partial move is done

I think the problem is that the user's movement is carried out without the consequence that it can cause in another square. The board really does have the correct position without the rook in the correct place after castling.

If in this position:
![image](https://user-images.githubusercontent.com/4182336/186383817-f6e6ea9d-6eab-4e82-99b4-c501e6f2ca90.png)

I do:
`event.chessboard.getPosition()`

I get incorrectly:
`rnbqkbr1/pppppp1p/6pn/8/2B1P3/5N2/PPPP1PPP/RNBQ2KR`

While in chess.js with **chess.fen()** i get:
`rnbqkbr1/pppppp1p/6pn/8/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b q - 3 4`

**Comment by shaack** [comment]
If you `getPosition` in `INPUT_EVENT_TYPE.moveDone` you get the position _before_ the move, because `moveDone` is a wrong name for the callback, it should better be called `validateDoneMoveInput` or so because this callback decides, if the move was valid but the move is not done at this time. 

Anyway, with version 5.2.0 I added a Promise called `this.chessboard.state.moveInputProcess` and I updated the example to work better: https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html (clear the cache before trying)

I changed the code in the callback:
```js
this.chessboard.state.moveInputProcess.then(() => { // wait for the move input process has finished
    this.chessboard.setPosition(chess.fen(), true).then(() => { // wait for animation has finished
```

Does this solve your problem?

**Comment by shaack** [comment]
With version 5.2.2 I renamed `INPUT_EVENT_TYPE.moveDone` to `INPUT_EVENT_TYPE.validateMoveInput`. See https://github.com/shaack/cm-chessboard/commit/b38b6aca1405c9da26cea09afe20860238699dd3
