### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Victor-Evogor** [shaack/cm-chessboard#97]
I feel typescript support is really necessary, it could ease development

**Comment by shaack** [comment]
Typescript is owned by Microsoft and I make free Software. Sorry.

**Comment by furkanmavili** [comment]
Github is also owned by Microsoft and you are using it??? @Victor-Evogor  I  will try to add type declerations but it will take some time 😞

**Comment by shaack** [comment]
ES6 is full compatible with TypeScript IMHO. But TypeScript not with ES6, and thats the problem. So why you need something like type declarations? I coded since 1999 with Microsoft software and I saw when they wanted to make the main browser language Visual Basic Script. Because market was 90% Internet Explorer and this seems possible. You maybe are to young to know this, so do what you want and learn your lesson. My software will never be based on something from Microsoft.

**Comment by Victor-Evogor** [comment]
Honestly I still don't see any reason why you don't want include typescript, it makes it more easy to use. atleast you don't have to glance at the docs back and forth. @furkanmavili That would be great, looking forward to it!

**Comment by shaack** [comment]
Well, I think, this is the wrong place for such a discussion. We could continue this on twitter, if you want. :) https://twitter.com/shaack

**Comment by matteoscaringi** [comment]
TypeScript is free and opensource 💀

**Comment by shaack** [comment]
Its "OpenSource", but not free. Further discussion on Twitter. please.
